# Docker compose file to test multi container application:
# API publisher, ShinyApp
version: '3.7'
services:
  plumber:
    image: vladdsm/docker-r-plumber
    name: API
  shiny:
    image: vladdsm/

networks:
  my-net:
    name: my-net    